using FluentJalium.Controls.Themes;
using FluentJalium.WinUI;
using Jalium.UI;
using Jalium.UI.Controls;
using Jalium.UI.Controls.Themes;
using WinUIGallery.Controls;

namespace FluentJalium.WinUI.Smoke;

internal static class Program
{
    [STAThread]
    private static void Main(string[] args)
    {
        var selfTest = args.Contains("--selftest");

        var app = new Application();
        ThemeManager.Initialize(app);
        FluentThemeManager.Apply(app);

        // After theming: the aliases replace plain Jalium type names process-wide, so the
        // framework's own dictionaries have to be parsed first.
        WinUICompatibility.Initialize();

        // Constructed from Controls/SampleThemeListener.xaml, copied byte-for-byte from the
        // WinUI Gallery. Its InitializeComponent is generated by Jalium's source generator from
        // the materialised .jalxaml copy of that file.
        var listener = new SampleThemeListener();

        Console.WriteLine($"SampleThemeListener -> {listener.GetType().FullName}");
        Console.WriteLine($"  base chain: {DescribeBaseChain(listener)}");

        if (selfTest)
        {
            Console.WriteLine("selftest passed");
            return;
        }

        app.Run(new MainWindow(listener));
    }

    private static string DescribeBaseChain(object instance)
    {
        var names = new List<string>();
        for (var type = instance.GetType(); type is not null && type != typeof(object); type = type.BaseType)
        {
            names.Add(type.Name);
        }

        return string.Join(" <- ", names);
    }

    private sealed class MainWindow : Window
    {
        public MainWindow(UIElement content)
        {
            Title = "FluentJalium.WinUI smoke";
            Width = 640;
            Height = 480;
            Content = content;
        }
    }
}
