using FluentJalium.Controls;
using FluentJalium.Themes;
using FluentJalium.Tests.Pixel;
using Jalium.UI;
using Jalium.UI.Controls;
using Jalium.UI.Controls.Primitives;
using Jalium.UI.Media;
using Xunit;

namespace FluentJalium.Tests;

/// <summary>
/// The arrival readings <c>docs/astra/audits/foreground.md</c> 7.2 was still missing for three named parts: the
/// tip's two title lines and the ComboBox dropdown's scroller. Two other names that section listed - the crumb
/// chevron and the tab icon host - have long had read-backs in <c>AstraBreadcrumbBarTests</c> and
/// <c>AstraTabViewTests</c>, and the sweep that started this file found the tip's parts were reachable all along;
/// what was missing was a reading of the brush the row writes onto them.
///
/// Each fact below reads the part for the instance its own row names. That much is easy to satisfy: all three
/// rows forward one palette brush (<c>TeachingTipForegroundBrush</c>, <c>TeachingTipTitleForegroundBrush</c> and
/// <c>TeachingTipSubtitleForegroundBrush</c> are a <c>StaticResource</c> chain to
/// <c>TextFillColorPrimaryBrush</c> at ThemeResources/TeachingTip.jalxaml:18-20, and so is
/// <c>ComboBoxDropDownForeground</c> at ThemeResources/ComboBox.jalxaml:109), and <see cref="DefaultTextInkTracksTheVariant"/>
/// measures that same brush to be what a label this runtime writes nothing on already carries, in both variants.
/// So deleting a row cannot be seen from the part: the row was deleted in three successive shapes - bare identity,
/// identity with a carrier ink written on the control, and the final five facts - and every reading stayed green
/// (spike/ForegroundArrival/mut-bare-*.log, mut-carrier-*.log, mut-del-*.log).
///
/// What these facts do have teeth for is the row's target. Re-pointing one row at another key moves exactly the
/// fact that names it and no other, with the part reading the re-pointed colour
/// (spike/ForegroundArrival/mut-swap-*.log). <see cref="A_carrier_ink_written_on_the_tip_does_not_reach_its_titled_labels"/>
/// is the other half of that: the parts these rows sit on are not reading anything by inheritance.
/// </summary>
[Collection(AstraThemeRuntimeCollection.Name)]
public sealed class AstraForegroundArrivalTests : IDisposable
{
    private readonly AstraThemeRuntimeFixture _fixture;
    private FluentTeachingTip? _tip;
    private ComboBox? _combo;

    public AstraForegroundArrivalTests(AstraThemeRuntimeFixture fixture)
    {
        _fixture = fixture;
        _fixture.Run(() =>
        {
            FluentThemeManager.ApplyTheme(FluentThemeVariant.Light);
            FluentThemeManager.ApplyAccent(null);
        });
    }

    /// <summary>An open tip and an open dropdown live on the shared host window, so both are closed here.</summary>
    public void Dispose()
    {
        _fixture.Run(() =>
        {
            CloseTip();
            CloseCombo();
            PixelHarness.Settle(20);
            FluentThemeManager.ApplyTheme(FluentThemeVariant.Light);
        });
    }

    /// <summary>
    /// Why deleting these three rows is invisible: a label that nothing writes on is not left without ink, and it
    /// is not reading its surroundings either - it carries the palette's primary text brush, in both variants. The
    /// same run shows what the presenter path does instead, which is the half #51 was about.
    /// </summary>
    [Fact]
    public void DefaultTextInkTracksTheVariant()
    {
        _fixture.Run(() =>
        {
            var carrier = Carrier();
            var direct = new TextBlock { Text = "passed through a presenter" };
            var passThrough = new ContentControl { Foreground = carrier, Content = direct };
            var generated = new ContentControl { Foreground = carrier, Content = "generated by the presenter" };
            var panel = new StackPanel();
            panel.Children.Add(passThrough);
            panel.Children.Add(generated);
            PixelHarness.Build(panel, 320, 120);
            PixelHarness.Settle(40);
            var generatedLabel = PixelHarness.Descendant<TextBlock>(generated)
                ?? throw new InvalidOperationException("The presenter generated no label.");

            Assert.Multiple(
                () => Assert.Same(Resource("TextFillColorPrimaryBrush"), direct.Foreground),
                () => Assert.Same(carrier, generatedLabel.Foreground));

            FluentThemeManager.ApplyTheme(FluentThemeVariant.Dark);
            PixelHarness.Settle(40);
            Assert.Multiple(
                () => Assert.Same(Resource("TextFillColorPrimaryBrush"), direct.Foreground),
                () => Assert.Same(carrier, generatedLabel.Foreground));
        });
    }

    [Fact]
    public void The_title_label_reads_the_brush_its_row_names()
    {
        _fixture.Run(() =>
        {
            OpenedTip();
            AssertRowOnLabel("TitleTextBlock", "TeachingTipTitleForegroundBrush");
        });
    }

    [Fact]
    public void The_subtitle_label_reads_the_brush_its_row_names()
    {
        _fixture.Run(() =>
        {
            OpenedTip();
            AssertRowOnLabel("SubtitleTextBlock", "TeachingTipSubtitleForegroundBrush");
        });
    }

    [Fact]
    public void A_carrier_ink_written_on_the_tip_does_not_reach_its_titled_labels()
    {
        // The inheritance side of the same question: the control's own ink reaches the text a presenter generates,
        // and reaches neither label the template names. Those two can only be painted by a row, which is what
        // the facts above read - and why this file writes the carrier to prove the reading is not ambient ink.
        _fixture.Run(() =>
        {
            var carrier = Carrier();
            OpenedTip(carrier);
            var content = PixelHarness.Descendant<TextBlock>(TipPart("MainContentPresenter"))
                ?? throw new InvalidOperationException("The tip's content never generated a label.");

            Assert.Multiple(
                () => Assert.Same(carrier, content.Foreground),
                () => Assert.NotSame(carrier, ((TextBlock)TipPart("TitleTextBlock")).Foreground),
                () => Assert.NotSame(carrier, ((TextBlock)TipPart("SubtitleTextBlock")).Foreground));
        });
    }

    [Fact]
    public void The_dropdown_scroller_reads_the_brush_its_row_names()
    {
        _fixture.Run(() =>
        {
            var combo = new ComboBox { Width = 220, Height = 32 };
            combo.Items.Add("Monday");
            PixelHarness.Build(combo, 220, 62);
            PixelHarness.Settle(30);
            _combo = combo;

            Brush? scroller;
            combo.IsDropDownOpen = true;
            PixelHarness.Settle(30);
            try
            {
                scroller = Named("PART_ScrollViewer").GetValue(TextBlock.ForegroundProperty) as Brush;
            }
            finally
            {
                // Closing on the failure path too: an open dropdown leaves its surface grafted into the shared
                // host's overlay for the next test to resolve by name (#47's family).
                combo.IsDropDownOpen = false;
                PixelHarness.Settle(20);
            }

            AssertRowWritten("the dropdown scroller", "ComboBoxDropDownForeground", scroller);
        });
    }

    private FluentTeachingTip OpenedTip(Brush? carrier = null)
    {
        CloseTip();
        var anchor = new Border { Width = 100, Height = 40 };
        var tip = new FluentTeachingTip
        {
            Target = anchor,
            Title = "Three shortcuts you already know",
            Subtitle = "Hold Ctrl and press a key.",
            Content = "The editor keeps a list of them under Help.",
            ActionButtonContent = "Got it",
            CloseButtonContent = "Dismiss",
            PreferredPlacement = FluentTeachingTipPlacementMode.Bottom,
            Foreground = carrier,
        };
        var surface = new Grid();
        surface.Children.Add(anchor);
        surface.Children.Add(tip);
        PixelHarness.Build(surface, 820, 620);
        PixelHarness.Settle(30);
        _tip = tip;
        tip.IsOpen = true;
        PixelHarness.Settle(60);
        return tip;
    }

    /// <summary>
    /// An ink no palette text token has: magenta. Written on a control it is the value a part would read if it
    /// were drawing on its surroundings instead of on a row.
    /// </summary>
    private static SolidColorBrush Carrier() => new(Color.FromRgb(0xFF, 0x00, 0xFF));

    private void AssertRowOnLabel(string part, string rowKey) =>
        AssertRowWritten(part, rowKey, ((TextBlock)TipPart(part)).Foreground);

    private static void AssertRowWritten(string part, string rowKey, Brush? brush)
    {
        var row = Resource(rowKey);
        Assert.True(
            ReferenceEquals(row, brush),
            $"{part} reads {Hex(brush)}, not the {Hex(row)} it carries when {rowKey} reaches it.");
    }

    private static string Hex(Brush? brush) =>
        brush is SolidColorBrush solid ? PixelHarness.Hex(solid.Color) : brush?.GetType().Name ?? "<null>";

    private void CloseTip()
    {
        if (_tip is { IsOpen: true } tip)
        {
            tip.IsOpen = false;
            PixelHarness.Settle(20);
        }

        _tip = null;
    }

    private void CloseCombo()
    {
        if (_combo is { IsDropDownOpen: true } combo)
        {
            combo.IsDropDownOpen = false;
        }

        _combo = null;
    }

    /// <summary>
    /// A part of the tip's card. The lookup starts at the tip's own <c>PART_Popup.Child</c>, not at the host
    /// window: a Popup with a placement target realizes its content in its own top-level PopupWindow
    /// (<c>Border &lt; PopupRoot &lt; PopupWindow</c>, spike/TeachingTipProbe), which is not a child of the host,
    /// so a host-window walk finds nothing. The ComboBox dropdown is the opposite case - the write grafts
    /// <c>PART_PopupBorder</c> and <c>PART_ScrollViewer</c> into the host's overlay layer
    /// (<c>AstraComboBoxTests</c>'s rung-0 reading), so that one is reached from the host.
    /// </summary>
    private FrameworkElement TipPart(string name)
    {
        var tip = _tip ?? throw new InvalidOperationException("No tip opened.");
        if (PixelHarness.Named(tip, "PART_Popup") is not Popup { Child: { } child })
        {
            throw new InvalidOperationException("The opened tip hosts no card.");
        }

        return PixelHarness.Named(child, name)
            ?? throw new InvalidOperationException($"No realized {name} in the tip's card.");
    }

    /// <summary>The dropdown's parts, grafted into the shared host's overlay layer when the popup opens.</summary>
    private static FrameworkElement Named(string name) =>
        PixelHarness.Named(PixelHarness.HostWindow(), name)
            ?? throw new InvalidOperationException($"No realized {name} under the host window.");

    /// <summary>
    /// The alias instance itself, through the same lookup the template row uses. <c>FluentThemeManager.GetBrush</c>
    /// reads only the generated palette and throws on these names, so an alias is looked up as a resource.
    /// </summary>
    private static Brush Resource(string key) =>
        Application.Current!.TryFindResource(key) as Brush
            ?? throw new InvalidOperationException($"{key} resolved to no brush.");
}
