//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentJalium.Gallery.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentJalium.Gallery.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture);
        public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture);
        public static string Settings_ThemeDescription => ResourceManager.GetString("Settings_ThemeDescription", resourceCulture);
        public static string Settings_ThemeLight => ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
        public static string Settings_ThemeDark => ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
        public static string Settings_ThemeHighContrast => ResourceManager.GetString("Settings_ThemeHighContrast", resourceCulture);
        public static string Settings_Accent => ResourceManager.GetString("Settings_Accent", resourceCulture);
        public static string Settings_AccentDescription => ResourceManager.GetString("Settings_AccentDescription", resourceCulture);
        public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture);
        public static string Settings_LanguageDescription => ResourceManager.GetString("Settings_LanguageDescription", resourceCulture);
        public static string Settings_Diagnostics => ResourceManager.GetString("Settings_Diagnostics", resourceCulture);
        public static string Settings_DiagnosticsDescription => ResourceManager.GetString("Settings_DiagnosticsDescription", resourceCulture);

        public static string Status_Theme => ResourceManager.GetString("Status_Theme", resourceCulture);
        public static string Status_Accent => ResourceManager.GetString("Status_Accent", resourceCulture);
        public static string Status_Language => ResourceManager.GetString("Status_Language", resourceCulture);

        public static string Diag_Shell => ResourceManager.GetString("Diag_Shell", resourceCulture);
        public static string Diag_ShellDesc => ResourceManager.GetString("Diag_ShellDesc", resourceCulture);
        public static string Diag_Catalog => ResourceManager.GetString("Diag_Catalog", resourceCulture);
        public static string Diag_CatalogDesc => ResourceManager.GetString("Diag_CatalogDesc", resourceCulture);
        public static string Diag_StateMatrix => ResourceManager.GetString("Diag_StateMatrix", resourceCulture);
        public static string Diag_StateMatrixDesc => ResourceManager.GetString("Diag_StateMatrixDesc", resourceCulture);
        public static string Diag_ShowMetadata => ResourceManager.GetString("Diag_ShowMetadata", resourceCulture);

        public static string Color_Blue => ResourceManager.GetString("Color_Blue", resourceCulture);
        public static string Color_Rose => ResourceManager.GetString("Color_Rose", resourceCulture);
        public static string Color_Orange => ResourceManager.GetString("Color_Orange", resourceCulture);
        public static string Color_Green => ResourceManager.GetString("Color_Green", resourceCulture);
    }
}
