//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentJalium.Gallery.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FluentJalium.Gallery.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }

        internal static string Settings_ThemeDescription {
            get {
                return ResourceManager.GetString("Settings_ThemeDescription", resourceCulture);
            }
        }

        internal static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }

        internal static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }

        internal static string Settings_ThemeHighContrast {
            get {
                return ResourceManager.GetString("Settings_ThemeHighContrast", resourceCulture);
            }
        }

        internal static string Settings_Accent {
            get {
                return ResourceManager.GetString("Settings_Accent", resourceCulture);
            }
        }

        internal static string Settings_AccentDescription {
            get {
                return ResourceManager.GetString("Settings_AccentDescription", resourceCulture);
            }
        }

        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }

        internal static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture);
            }
        }

        internal static string Settings_Diagnostics {
            get {
                return ResourceManager.GetString("Settings_Diagnostics", resourceCulture);
            }
        }

        internal static string Settings_DiagnosticsDescription {
            get {
                return ResourceManager.GetString("Settings_DiagnosticsDescription", resourceCulture);
            }
        }

        internal static string Status_Theme {
            get {
                return ResourceManager.GetString("Status_Theme", resourceCulture);
            }
        }

        internal static string Status_Accent {
            get {
                return ResourceManager.GetString("Status_Accent", resourceCulture);
            }
        }

        internal static string Status_Language {
            get {
                return ResourceManager.GetString("Status_Language", resourceCulture);
            }
        }

        internal static string Diag_Shell {
            get {
                return ResourceManager.GetString("Diag_Shell", resourceCulture);
            }
        }

        internal static string Diag_ShellDesc {
            get {
                return ResourceManager.GetString("Diag_ShellDesc", resourceCulture);
            }
        }

        internal static string Diag_Catalog {
            get {
                return ResourceManager.GetString("Diag_Catalog", resourceCulture);
            }
        }

        internal static string Diag_CatalogDesc {
            get {
                return ResourceManager.GetString("Diag_CatalogDesc", resourceCulture);
            }
        }

        internal static string Diag_StateMatrix {
            get {
                return ResourceManager.GetString("Diag_StateMatrix", resourceCulture);
            }
        }

        internal static string Diag_StateMatrixDesc {
            get {
                return ResourceManager.GetString("Diag_StateMatrixDesc", resourceCulture);
            }
        }

        internal static string Diag_ShowMetadata {
            get {
                return ResourceManager.GetString("Diag_ShowMetadata", resourceCulture);
            }
        }

        internal static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }

        internal static string Color_Rose {
            get {
                return ResourceManager.GetString("Color_Rose", resourceCulture);
            }
        }

        internal static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }

        internal static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }

        internal static string Buttons_Title {
            get {
                return ResourceManager.GetString("Buttons_Title", resourceCulture);
            }
        }

        internal static string Buttons_Surface_Title {
            get {
                return ResourceManager.GetString("Buttons_Surface_Title", resourceCulture);
            }
        }

        internal static string Buttons_Surface_Description {
            get {
                return ResourceManager.GetString("Buttons_Surface_Description", resourceCulture);
            }
        }

        internal static string Buttons_Split_Title {
            get {
                return ResourceManager.GetString("Buttons_Split_Title", resourceCulture);
            }
        }

        internal static string Buttons_Split_Description {
            get {
                return ResourceManager.GetString("Buttons_Split_Description", resourceCulture);
            }
        }

        internal static string Buttons_CommandBar_Title {
            get {
                return ResourceManager.GetString("Buttons_CommandBar_Title", resourceCulture);
            }
        }

        internal static string Buttons_CommandBar_Description {
            get {
                return ResourceManager.GetString("Buttons_CommandBar_Description", resourceCulture);
            }
        }

        internal static string Button_Label_Button {
            get {
                return ResourceManager.GetString("Button_Label_Button", resourceCulture);
            }
        }

        internal static string Button_Label_Repeat {
            get {
                return ResourceManager.GetString("Button_Label_Repeat", resourceCulture);
            }
        }

        internal static string Button_Label_Link {
            get {
                return ResourceManager.GetString("Button_Label_Link", resourceCulture);
            }
        }

        internal static string Button_Label_Menu {
            get {
                return ResourceManager.GetString("Button_Label_Menu", resourceCulture);
            }
        }

        internal static string Button_Label_Disabled {
            get {
                return ResourceManager.GetString("Button_Label_Disabled", resourceCulture);
            }
        }

        internal static string Button_Label_Split {
            get {
                return ResourceManager.GetString("Button_Label_Split", resourceCulture);
            }
        }

        internal static string Button_Label_Toggle {
            get {
                return ResourceManager.GetString("Button_Label_Toggle", resourceCulture);
            }
        }

        internal static string SampleCard_Output {
            get {
                return ResourceManager.GetString("SampleCard_Output", resourceCulture);
            }
        }

        internal static string SampleCard_Options {
            get {
                return ResourceManager.GetString("SampleCard_Options", resourceCulture);
            }
        }

        internal static string SampleCard_Code {
            get {
                return ResourceManager.GetString("SampleCard_Code", resourceCulture);
            }
        }

        internal static string Options_MinWidth {
            get {
                return ResourceManager.GetString("Options_MinWidth", resourceCulture);
            }
        }

        internal static string Options_Width {
            get {
                return ResourceManager.GetString("Options_Width", resourceCulture);
            }
        }

        internal static string Options_State {
            get {
                return ResourceManager.GetString("Options_State", resourceCulture);
            }
        }

        internal static string Options_IsEnabled {
            get {
                return ResourceManager.GetString("Options_IsEnabled", resourceCulture);
            }
        }

        internal static string Options_IsVisible {
            get {
                return ResourceManager.GetString("Options_IsVisible", resourceCulture);
            }
        }

        internal static string Options_IsChecked {
            get {
                return ResourceManager.GetString("Options_IsChecked", resourceCulture);
            }
        }

        internal static string Options_IsOpen {
            get {
                return ResourceManager.GetString("Options_IsOpen", resourceCulture);
            }
        }

        internal static string Options_LabelPosition {
            get {
                return ResourceManager.GetString("Options_LabelPosition", resourceCulture);
            }
        }

        internal static string Options_LabelPosition_Right {
            get {
                return ResourceManager.GetString("Options_LabelPosition_Right", resourceCulture);
            }
        }

        internal static string Options_LabelPosition_Bottom {
            get {
                return ResourceManager.GetString("Options_LabelPosition_Bottom", resourceCulture);
            }
        }

        internal static string Options_LabelPosition_Collapsed {
            get {
                return ResourceManager.GetString("Options_LabelPosition_Collapsed", resourceCulture);
            }
        }

        internal static string Output_Ready {
            get {
                return ResourceManager.GetString("Output_Ready", resourceCulture);
            }
        }

        internal static string Output_ButtonClicked {
            get {
                return ResourceManager.GetString("Output_ButtonClicked", resourceCulture);
            }
        }

        internal static string Output_SplitClicked {
            get {
                return ResourceManager.GetString("Output_SplitClicked", resourceCulture);
            }
        }

        internal static string Output_Opening {
            get {
                return ResourceManager.GetString("Output_Opening", resourceCulture);
            }
        }

        internal static string Output_Opened {
            get {
                return ResourceManager.GetString("Output_Opened", resourceCulture);
            }
        }

        internal static string Output_Closed {
            get {
                return ResourceManager.GetString("Output_Closed", resourceCulture);
            }
        }

        internal static string Output_Repeat {
            get {
                return ResourceManager.GetString("Output_Repeat", resourceCulture);
            }
        }

        internal static string Output_Checked {
            get {
                return ResourceManager.GetString("Output_Checked", resourceCulture);
            }
        }

        internal static string Command_Add {
            get {
                return ResourceManager.GetString("Command_Add", resourceCulture);
            }
        }

        internal static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }

        internal static string Command_Share {
            get {
                return ResourceManager.GetString("Command_Share", resourceCulture);
            }
        }

        internal static string Command_Pin {
            get {
                return ResourceManager.GetString("Command_Pin", resourceCulture);
            }
        }

        internal static string Command_Settings {
            get {
                return ResourceManager.GetString("Command_Settings", resourceCulture);
            }
        }

        internal static string Command_Open {
            get {
                return ResourceManager.GetString("Command_Open", resourceCulture);
            }
        }

        internal static string Command_Create {
            get {
                return ResourceManager.GetString("Command_Create", resourceCulture);
            }
        }

        internal static string Command_Export {
            get {
                return ResourceManager.GetString("Command_Export", resourceCulture);
            }
        }

        internal static string Command_Clicked {
            get {
                return ResourceManager.GetString("Command_Clicked", resourceCulture);
            }
        }
    }
}
