//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentJalium.Gallery.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FluentJalium.Gallery.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }

        internal static string Settings_ThemeDescription {
            get {
                return ResourceManager.GetString("Settings_ThemeDescription", resourceCulture);
            }
        }

        internal static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }

        internal static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }

        internal static string Settings_ThemeHighContrast {
            get {
                return ResourceManager.GetString("Settings_ThemeHighContrast", resourceCulture);
            }
        }

        internal static string Settings_Accent {
            get {
                return ResourceManager.GetString("Settings_Accent", resourceCulture);
            }
        }

        internal static string Settings_AccentDescription {
            get {
                return ResourceManager.GetString("Settings_AccentDescription", resourceCulture);
            }
        }

        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }

        internal static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture);
            }
        }

        internal static string Settings_Diagnostics {
            get {
                return ResourceManager.GetString("Settings_Diagnostics", resourceCulture);
            }
        }

        internal static string Settings_DiagnosticsDescription {
            get {
                return ResourceManager.GetString("Settings_DiagnosticsDescription", resourceCulture);
            }
        }

        internal static string Status_Theme {
            get {
                return ResourceManager.GetString("Status_Theme", resourceCulture);
            }
        }

        internal static string Status_Accent {
            get {
                return ResourceManager.GetString("Status_Accent", resourceCulture);
            }
        }

        internal static string Status_Language {
            get {
                return ResourceManager.GetString("Status_Language", resourceCulture);
            }
        }

        internal static string Diag_Shell {
            get {
                return ResourceManager.GetString("Diag_Shell", resourceCulture);
            }
        }

        internal static string Diag_ShellDesc {
            get {
                return ResourceManager.GetString("Diag_ShellDesc", resourceCulture);
            }
        }

        internal static string Diag_Catalog {
            get {
                return ResourceManager.GetString("Diag_Catalog", resourceCulture);
            }
        }

        internal static string Diag_CatalogDesc {
            get {
                return ResourceManager.GetString("Diag_CatalogDesc", resourceCulture);
            }
        }

        internal static string Diag_StateMatrix {
            get {
                return ResourceManager.GetString("Diag_StateMatrix", resourceCulture);
            }
        }

        internal static string Diag_StateMatrixDesc {
            get {
                return ResourceManager.GetString("Diag_StateMatrixDesc", resourceCulture);
            }
        }

        internal static string Diag_ShowMetadata {
            get {
                return ResourceManager.GetString("Diag_ShowMetadata", resourceCulture);
            }
        }

        internal static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }

        internal static string Color_Rose {
            get {
                return ResourceManager.GetString("Color_Rose", resourceCulture);
            }
        }

        internal static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }

        internal static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }

        internal static string Buttons_Title {
            get {
                return ResourceManager.GetString("Buttons_Title", resourceCulture);
            }
        }

        internal static string Buttons_Surface_Title {
            get {
                return ResourceManager.GetString("Buttons_Surface_Title", resourceCulture);
            }
        }

        internal static string Buttons_Surface_Description {
            get {
                return ResourceManager.GetString("Buttons_Surface_Description", resourceCulture);
            }
        }

        internal static string Buttons_Split_Title {
            get {
                return ResourceManager.GetString("Buttons_Split_Title", resourceCulture);
            }
        }

        internal static string Buttons_Split_Description {
            get {
                return ResourceManager.GetString("Buttons_Split_Description", resourceCulture);
            }
        }

        internal static string Buttons_CommandBar_Title {
            get {
                return ResourceManager.GetString("Buttons_CommandBar_Title", resourceCulture);
            }
        }

        internal static string Buttons_CommandBar_Description {
            get {
                return ResourceManager.GetString("Buttons_CommandBar_Description", resourceCulture);
            }
        }

        internal static string Button_Label_Button {
            get {
                return ResourceManager.GetString("Button_Label_Button", resourceCulture);
            }
        }

        internal static string Button_Label_Repeat {
            get {
                return ResourceManager.GetString("Button_Label_Repeat", resourceCulture);
            }
        }

        internal static string Button_Label_Link {
            get {
                return ResourceManager.GetString("Button_Label_Link", resourceCulture);
            }
        }

        internal static string Button_Label_Menu {
            get {
                return ResourceManager.GetString("Button_Label_Menu", resourceCulture);
            }
        }

        internal static string Button_Label_Disabled {
            get {
                return ResourceManager.GetString("Button_Label_Disabled", resourceCulture);
            }
        }

        internal static string Button_Label_Split {
            get {
                return ResourceManager.GetString("Button_Label_Split", resourceCulture);
            }
        }

        internal static string Button_Label_Toggle {
            get {
                return ResourceManager.GetString("Button_Label_Toggle", resourceCulture);
            }
        }

        internal static string SampleCard_Output {
            get {
                return ResourceManager.GetString("SampleCard_Output", resourceCulture);
            }
        }

        internal static string SampleCard_Options {
            get {
                return ResourceManager.GetString("SampleCard_Options", resourceCulture);
            }
        }

        internal static string SampleCard_Code {
            get {
                return ResourceManager.GetString("SampleCard_Code", resourceCulture);
            }
        }

        internal static string Options_MinWidth {
            get {
                return ResourceManager.GetString("Options_MinWidth", resourceCulture);
            }
        }

        internal static string Options_Width {
            get {
                return ResourceManager.GetString("Options_Width", resourceCulture);
            }
        }

        internal static string Options_State {
            get {
                return ResourceManager.GetString("Options_State", resourceCulture);
            }
        }

        internal static string Options_IsEnabled {
            get {
                return ResourceManager.GetString("Options_IsEnabled", resourceCulture);
            }
        }

        internal static string Options_IsVisible {
            get {
                return ResourceManager.GetString("Options_IsVisible", resourceCulture);
            }
        }

        internal static string Options_IsChecked {
            get {
                return ResourceManager.GetString("Options_IsChecked", resourceCulture);
            }
        }

        internal static string Options_IsOpen {
            get {
                return ResourceManager.GetString("Options_IsOpen", resourceCulture);
            }
        }

        internal static string Options_LabelPosition {
            get {
                return ResourceManager.GetString("Options_LabelPosition", resourceCulture);
            }
        }

        internal static string Options_LabelPosition_Right {
            get {
                return ResourceManager.GetString("Options_LabelPosition_Right", resourceCulture);
            }
        }

        internal static string Options_LabelPosition_Bottom {
            get {
                return ResourceManager.GetString("Options_LabelPosition_Bottom", resourceCulture);
            }
        }

        internal static string Options_LabelPosition_Collapsed {
            get {
                return ResourceManager.GetString("Options_LabelPosition_Collapsed", resourceCulture);
            }
        }

        internal static string Output_Ready {
            get {
                return ResourceManager.GetString("Output_Ready", resourceCulture);
            }
        }

        internal static string Output_ButtonClicked {
            get {
                return ResourceManager.GetString("Output_ButtonClicked", resourceCulture);
            }
        }

        internal static string Output_SplitClicked {
            get {
                return ResourceManager.GetString("Output_SplitClicked", resourceCulture);
            }
        }

        internal static string Output_Opening {
            get {
                return ResourceManager.GetString("Output_Opening", resourceCulture);
            }
        }

        internal static string Output_Opened {
            get {
                return ResourceManager.GetString("Output_Opened", resourceCulture);
            }
        }

        internal static string Output_Closed {
            get {
                return ResourceManager.GetString("Output_Closed", resourceCulture);
            }
        }

        internal static string Output_Repeat {
            get {
                return ResourceManager.GetString("Output_Repeat", resourceCulture);
            }
        }

        internal static string Output_Checked {
            get {
                return ResourceManager.GetString("Output_Checked", resourceCulture);
            }
        }

        internal static string Command_Add {
            get {
                return ResourceManager.GetString("Command_Add", resourceCulture);
            }
        }

        internal static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }

        internal static string Command_Share {
            get {
                return ResourceManager.GetString("Command_Share", resourceCulture);
            }
        }

        internal static string Command_Pin {
            get {
                return ResourceManager.GetString("Command_Pin", resourceCulture);
            }
        }

        internal static string Command_Settings {
            get {
                return ResourceManager.GetString("Command_Settings", resourceCulture);
            }
        }

        internal static string Command_Open {
            get {
                return ResourceManager.GetString("Command_Open", resourceCulture);
            }
        }

        internal static string Command_Create {
            get {
                return ResourceManager.GetString("Command_Create", resourceCulture);
            }
        }

        internal static string Command_Export {
            get {
                return ResourceManager.GetString("Command_Export", resourceCulture);
            }
        }

        internal static string Command_Clicked {
            get {
                return ResourceManager.GetString("Command_Clicked", resourceCulture);
            }
        }

        internal static string Shell_Title {
            get {
                return ResourceManager.GetString("Shell_Title", resourceCulture);
            }
        }

        internal static string Shell_Subtitle {
            get {
                return ResourceManager.GetString("Shell_Subtitle", resourceCulture);
            }
        }

        internal static string Shell_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Shell_SearchPlaceholder", resourceCulture);
            }
        }

        internal static string Shell_Language {
            get {
                return ResourceManager.GetString("Shell_Language", resourceCulture);
            }
        }

        internal static string Shell_NoResults {
            get {
                return ResourceManager.GetString("Shell_NoResults", resourceCulture);
            }
        }

        internal static string Overview_Title {
            get {
                return ResourceManager.GetString("Overview_Title", resourceCulture);
            }
        }

        internal static string Overview_ThemeVariants {
            get {
                return ResourceManager.GetString("Overview_ThemeVariants", resourceCulture);
            }
        }

        internal static string Overview_ThemeVariants_Desc {
            get {
                return ResourceManager.GetString("Overview_ThemeVariants_Desc", resourceCulture);
            }
        }

        internal static string Overview_AccentPalette {
            get {
                return ResourceManager.GetString("Overview_AccentPalette", resourceCulture);
            }
        }

        internal static string Overview_AccentPalette_Desc {
            get {
                return ResourceManager.GetString("Overview_AccentPalette_Desc", resourceCulture);
            }
        }

        internal static string Overview_TypographyTokens {
            get {
                return ResourceManager.GetString("Overview_TypographyTokens", resourceCulture);
            }
        }

        internal static string Overview_TypographyTokens_Desc {
            get {
                return ResourceManager.GetString("Overview_TypographyTokens_Desc", resourceCulture);
            }
        }

        internal static string Overview_MaterialPreview {
            get {
                return ResourceManager.GetString("Overview_MaterialPreview", resourceCulture);
            }
        }

        internal static string Overview_MaterialPreview_Desc {
            get {
                return ResourceManager.GetString("Overview_MaterialPreview_Desc", resourceCulture);
            }
        }

        internal static string Overview_Theme {
            get {
                return ResourceManager.GetString("Overview_Theme", resourceCulture);
            }
        }

        internal static string Overview_Accent {
            get {
                return ResourceManager.GetString("Overview_Accent", resourceCulture);
            }
        }

        internal static string Overview_Material_Active {
            get {
                return ResourceManager.GetString("Overview_Material_Active", resourceCulture);
            }
        }

        internal static string Overview_ResourceLayer {
            get {
                return ResourceManager.GetString("Overview_ResourceLayer", resourceCulture);
            }
        }

        internal static string Overview_ResourceLayer_Desc {
            get {
                return ResourceManager.GetString("Overview_ResourceLayer_Desc", resourceCulture);
            }
        }

        internal static string Overview_Settings {
            get {
                return ResourceManager.GetString("Overview_Settings", resourceCulture);
            }
        }

        internal static string Overview_BackdropAware {
            get {
                return ResourceManager.GetString("Overview_BackdropAware", resourceCulture);
            }
        }

        internal static string Overview_MaterialAccent {
            get {
                return ResourceManager.GetString("Overview_MaterialAccent", resourceCulture);
            }
        }

        internal static string Overview_Typography_Display {
            get {
                return ResourceManager.GetString("Overview_Typography_Display", resourceCulture);
            }
        }

        internal static string Overview_Typography_Body {
            get {
                return ResourceManager.GetString("Overview_Typography_Body", resourceCulture);
            }
        }

        internal static string Overview_Typography_Mono {
            get {
                return ResourceManager.GetString("Overview_Typography_Mono", resourceCulture);
            }
        }

        internal static string Overview_Typography_DisplaySample {
            get {
                return ResourceManager.GetString("Overview_Typography_DisplaySample", resourceCulture);
            }
        }

        internal static string Overview_Typography_BodySample {
            get {
                return ResourceManager.GetString("Overview_Typography_BodySample", resourceCulture);
            }
        }

        internal static string Switches_Title {
            get {
                return ResourceManager.GetString("Switches_Title", resourceCulture);
            }
        }

        internal static string Switches_ToggleButton {
            get {
                return ResourceManager.GetString("Switches_ToggleButton", resourceCulture);
            }
        }

        internal static string Switches_ToggleButton_Desc {
            get {
                return ResourceManager.GetString("Switches_ToggleButton_Desc", resourceCulture);
            }
        }

        internal static string Switches_ToggleSwitch {
            get {
                return ResourceManager.GetString("Switches_ToggleSwitch", resourceCulture);
            }
        }

        internal static string Switches_ToggleSwitch_Desc {
            get {
                return ResourceManager.GetString("Switches_ToggleSwitch_Desc", resourceCulture);
            }
        }

        internal static string Switches_Events {
            get {
                return ResourceManager.GetString("Switches_Events", resourceCulture);
            }
        }

        internal static string Switches_Events_Desc {
            get {
                return ResourceManager.GetString("Switches_Events_Desc", resourceCulture);
            }
        }

        internal static string Switches_MaterialRow {
            get {
                return ResourceManager.GetString("Switches_MaterialRow", resourceCulture);
            }
        }

        internal static string Switches_MaterialRow_Desc {
            get {
                return ResourceManager.GetString("Switches_MaterialRow_Desc", resourceCulture);
            }
        }

        internal static string Switches_StateWaiting {
            get {
                return ResourceManager.GetString("Switches_StateWaiting", resourceCulture);
            }
        }

        internal static string Switches_StateChecked {
            get {
                return ResourceManager.GetString("Switches_StateChecked", resourceCulture);
            }
        }

        internal static string Switches_StateUnchecked {
            get {
                return ResourceManager.GetString("Switches_StateUnchecked", resourceCulture);
            }
        }

        internal static string Switches_StateIndeterminate {
            get {
                return ResourceManager.GetString("Switches_StateIndeterminate", resourceCulture);
            }
        }

        internal static string Switches_LiveSetting {
            get {
                return ResourceManager.GetString("Switches_LiveSetting", resourceCulture);
            }
        }

        internal static string Switches_LiveSetting_Desc {
            get {
                return ResourceManager.GetString("Switches_LiveSetting_Desc", resourceCulture);
            }
        }

        internal static string Switches_LiveOutput {
            get {
                return ResourceManager.GetString("Switches_LiveOutput", resourceCulture);
            }
        }

        internal static string Switches_TurnOn {
            get {
                return ResourceManager.GetString("Switches_TurnOn", resourceCulture);
            }
        }

        internal static string Switches_TurnOff {
            get {
                return ResourceManager.GetString("Switches_TurnOff", resourceCulture);
            }
        }

        internal static string Switches_Flip {
            get {
                return ResourceManager.GetString("Switches_Flip", resourceCulture);
            }
        }

        internal static string Switches_Density {
            get {
                return ResourceManager.GetString("Switches_Density", resourceCulture);
            }
        }

        internal static string Switches_MicaLayer {
            get {
                return ResourceManager.GetString("Switches_MicaLayer", resourceCulture);
            }
        }

        internal static string Switches_MicaLayer_Desc {
            get {
                return ResourceManager.GetString("Switches_MicaLayer_Desc", resourceCulture);
            }
        }

        internal static string Switches_AcrylicPass {
            get {
                return ResourceManager.GetString("Switches_AcrylicPass", resourceCulture);
            }
        }

        internal static string Switches_AcrylicPass_Desc {
            get {
                return ResourceManager.GetString("Switches_AcrylicPass_Desc", resourceCulture);
            }
        }

        internal static string Switches_ReducedMotion {
            get {
                return ResourceManager.GetString("Switches_ReducedMotion", resourceCulture);
            }
        }

        internal static string Switches_ReducedMotion_Desc {
            get {
                return ResourceManager.GetString("Switches_ReducedMotion_Desc", resourceCulture);
            }
        }

        internal static string Switches_On {
            get {
                return ResourceManager.GetString("Switches_On", resourceCulture);
            }
        }

        internal static string Switches_Off {
            get {
                return ResourceManager.GetString("Switches_Off", resourceCulture);
            }
        }

        internal static string Switches_Mixed {
            get {
                return ResourceManager.GetString("Switches_Mixed", resourceCulture);
            }
        }

        internal static string Switches_Default {
            get {
                return ResourceManager.GetString("Switches_Default", resourceCulture);
            }
        }

        internal static string Switches_Status {
            get {
                return ResourceManager.GetString("Switches_Status", resourceCulture);
            }
        }

        internal static string Switches_ComfortableRow {
            get {
                return ResourceManager.GetString("Switches_ComfortableRow", resourceCulture);
            }
        }

        internal static string Switches_Paused {
            get {
                return ResourceManager.GetString("Switches_Paused", resourceCulture);
            }
        }

        internal static string Switches_Running {
            get {
                return ResourceManager.GetString("Switches_Running", resourceCulture);
            }
        }

        internal static string Switches_SpaciousDisabledRow {
            get {
                return ResourceManager.GetString("Switches_SpaciousDisabledRow", resourceCulture);
            }
        }

        internal static string Switches_NotificationsOff {
            get {
                return ResourceManager.GetString("Switches_NotificationsOff", resourceCulture);
            }
        }

        internal static string Switches_NotificationsOn {
            get {
                return ResourceManager.GetString("Switches_NotificationsOn", resourceCulture);
            }
        }

        internal static string Switches_Density_Compact {
            get {
                return ResourceManager.GetString("Switches_Density_Compact", resourceCulture);
            }
        }

        internal static string Switches_Density_Comfortable {
            get {
                return ResourceManager.GetString("Switches_Density_Comfortable", resourceCulture);
            }
        }

        internal static string Switches_Density_Spacious {
            get {
                return ResourceManager.GetString("Switches_Density_Spacious", resourceCulture);
            }
        }
    }
}
