using System.Xml.Linq;

namespace FluentJalium.Tests.Resources;

/// <summary>
/// Locks <c>docs/astra/audits/keys.md</c> - the published inventory of every resource key the layer
/// carries - against the dictionaries themselves. The list is generated by
/// <c>tools/Report-AstraResourceKeys.ps1</c> with a line-based reader; this class reads the same files
/// with <see cref="XDocument"/> and compares the two, so the inventory cannot drift in either direction:
/// a key added without re-running the tool fails, and so does an entry a hand edit invented.
/// </summary>
/// <remarks>
/// Two independent parsers agreeing is the point. A test that re-ran the generator's own rules would only
/// prove the document is self-consistent, which is what the tool's <c>-Check</c> mode already reports.
/// </remarks>
public sealed class AstraPublicKeysInventoryTests
{
    private static readonly XNamespace Xaml = "http://schemas.microsoft.com/winfx/2006/xaml";

    private const string InventoryPath = "docs/astra/audits/keys.md";

    [Fact]
    public void The_inventory_names_every_key_the_dictionaries_publish()
    {
        var rows = Rows();
        var published = rows.Where(row => row.Key.Length > 0).Select(row => row.Key).ToHashSet(StringComparer.Ordinal);
        var documented = DocumentedKeys();

        var missing = published.Except(documented).OrderBy(name => name, StringComparer.Ordinal).ToList();
        var invented = documented.Except(published).OrderBy(name => name, StringComparer.Ordinal).ToList();

        Assert.True(missing.Count == 0 && invented.Count == 0,
            $"{InventoryPath} no longer matches the dictionaries (missing={missing.Count}, invented={invented.Count}). " +
            "Regenerate it with tools/Report-AstraResourceKeys.ps1 and commit both." + Environment.NewLine +
            "Not in the document: " + string.Join(", ", missing.Take(20)) + Environment.NewLine +
            "Not in the dictionaries: " + string.Join(", ", invented.Take(20)));
    }

    /// <summary>
    /// The count line is what a reader trusts first, so it has to be a read-back rather than prose: every
    /// row is counted here from the files, including the implicit styles the name list cannot carry.
    /// </summary>
    [Fact]
    public void The_documented_totals_match_the_rows_the_files_hold()
    {
        var rows = Rows();
        var totals = Assert.Single(
            File.ReadAllLines(Locate(InventoryPath)), line => line.StartsWith("Totals: ", StringComparison.Ordinal));

        Assert.Contains($"{rows.Count} keyed or implicit rows", totals, StringComparison.Ordinal);
        foreach (var layer in new[] { "palette", "token", "style" })
        {
            Assert.Contains($"{rows.Count(row => row.Layer == layer)} {layer}", totals, StringComparison.Ordinal);
        }
    }

    private sealed record Row(string File, string Layer, string Type, string Key);

    private static List<Row> Rows()
    {
        var rows = new List<Row>();
        foreach (var (file, layer) in Files())
        {
            var root = XDocument.Load(Locate($"src/FluentJalium/{file}")).Root!;
            foreach (var element in root.Descendants())
            {
                if (element.Name.LocalName == "ResourceDictionary")
                {
                    continue;
                }

                var key = element.Attribute(Xaml + "Key")?.Value;
                if (key is not null)
                {
                    rows.Add(new Row(file, layer, element.Name.LocalName, key));
                }
                else if (element.Name.LocalName == "Style")
                {
                    // A style with no key is published by type, and the document lists it as *(implicit)*.
                    rows.Add(new Row(file, layer, "ImplicitStyle", string.Empty));
                }
            }
        }

        return rows;
    }

    /// <summary>
    /// Table rows read <c>| type | `key` | target or value |</c>. The implicit-style rows hold
    /// <c>*(implicit)*</c> where the key belongs and the high-contrast map rows put the key in the first
    /// column, so both are recognisable and skipped here - the map's names are the palette's own
    /// <c>*Brush</c> keys, which the palette tables already list.
    /// </summary>
    private static HashSet<string> DocumentedKeys()
    {
        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (var line in File.ReadAllLines(Locate(InventoryPath)))
        {
            if (!line.StartsWith("| ", StringComparison.Ordinal))
            {
                continue;
            }

            var cells = line.Split('|');
            if (cells.Length < 4 || cells[1].Trim().StartsWith('`') || cells[2].Trim() == "key")
            {
                continue;
            }

            var key = cells[2].Trim();
            if (key.Length > 2 && key[0] == '`' && key[^1] == '`')
            {
                keys.Add(key[1..^1]);
            }
        }

        return keys;
    }

    private static IEnumerable<(string File, string Layer)> Files()
    {
        yield return ("ThemeResources/Light.jalxaml", "palette");
        yield return ("ThemeResources/Dark.jalxaml", "palette");

        foreach (var raw in File.ReadAllLines(Locate("src/FluentJalium/Themes/Manifest.txt")))
        {
            var entry = raw.Split('#')[0].Trim();
            if (entry.Length > 0)
            {
                yield return (entry, entry.StartsWith("Styles/", StringComparison.Ordinal) ? "style" : "token");
            }
        }
    }

    private static string Locate(string relative) => System.IO.Path.Combine(
        RepositoryRoot(), relative.Replace('/', System.IO.Path.DirectorySeparatorChar));

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(System.IO.Path.Combine(directory.FullName, "FluentJalium.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Cannot locate the repository root.");
    }
}
