<#
.SYNOPSIS
  Generates docs/astra/audits/keys.md - the inventory of every resource key the Astra layer publishes.
.DESCRIPTION
  Reads the load manifest (src/FluentJalium/Themes/Manifest.txt) plus the palette dictionaries and lists
  each keyed row it finds: alias target for StaticResource rows, value for literal rows, target type for
  styles. Also lists the implicit styles, which have a target type but no key.

  The tail of the file carries a canonical-line count and a SHA-256 over those same lines. A test recomputes
  them and fails on drift, so this tool is how a deliberate change gets recorded:

    powershell -File tools/Report-AstraResourceKeys.ps1          # rewrite keys.md
    powershell -File tools/Report-AstraResourceKeys.ps1 -Check   # exit 1 if keys.md is stale
#>
[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$src = Join-Path $repo 'src/FluentJalium'
$out = Join-Path $repo 'docs/astra/audits/keys.md'

function Read-Source([string]$path) {
    $text = [IO.File]::ReadAllText($path)
    # A comment can name a key in prose; strip every comment block before looking for rows.
    return [Regex]::Replace($text, '<!--.*?-->', '', 'Singleline')
}

# One row per keyed element: file, type, key, target/value, layer.
function Get-Rows([string]$file, [string]$layer) {
    $path = Join-Path $src $file
    if (-not (Test-Path -LiteralPath $path)) { return @() }
    $text = Read-Source $path
    $rows = [System.Collections.Generic.List[object]]::new()
    foreach ($match in [Regex]::Matches($text, '<([A-Za-z][A-Za-z0-9.]*)\s+([^>]*?)/?>')) {
        $type = $match.Groups[1].Value
        $attrs = $match.Groups[2].Value
        $key = [Regex]::Match($attrs, 'x:Key="([^"]*)"')
        $tail = $match.Value
        if ($type -eq 'ResourceDictionary') { continue }
        if ($key.Success) {
            $resource = [Regex]::Match($attrs, 'ResourceKey="([^"]*)"')
            $color = [Regex]::Match($attrs, 'Color="([^"]*)"')
            $targetType = [Regex]::Match($attrs, 'TargetType="([^"]*)"')
            $value = ''
            if ($resource.Success) { $value = $resource.Groups[1].Value }
            elseif ($color.Success) { $value = $color.Groups[1].Value }
            elseif ($targetType.Success) { $value = $targetType.Groups[1].Value }
            elseif ($tail -notmatch '/>$') {
                $body = [Regex]::Match($text.Substring($match.Index), ('(?s)<[A-Za-z][A-Za-z0-9.]*\s+[^>]*?>(.*?)</' + [Regex]::Escape($type) + '>'))
                if ($body.Success) { $value = $body.Groups[1].Value.Trim() }
            }
            $rows.Add([pscustomobject]@{
                    File = $file; Layer = $layer; Type = $type; Key = $key.Groups[1].Value; Target = $value
                })
        }
        elseif ($type -eq 'Style') {
            $targetType = [Regex]::Match($attrs, 'TargetType="([^"]*)"')
            if ($targetType.Success) {
                $rows.Add([pscustomobject]@{
                        File = $file; Layer = $layer; Type = 'ImplicitStyle'; Key = ''; Target = $targetType.Groups[1].Value
                    })
            }
        }
    }
    return $rows.ToArray()
}

$manifest = Join-Path $src 'Themes/Manifest.txt'
$entries = Get-Content -LiteralPath $manifest |
    ForEach-Object { ($_ -split '#')[0].Trim() } |
    Where-Object { $_ }

$palette = @('ThemeResources/Light.jalxaml', 'ThemeResources/Dark.jalxaml')
$rows = [System.Collections.Generic.List[object]]::new()
foreach ($file in $palette) { $rows.AddRange(@(Get-Rows $file 'palette')) }
foreach ($file in $entries) {
    $layer = if ($file -like 'Styles/*') { 'style' } else { 'token' }
    $rows.AddRange(@(Get-Rows $file $layer))
}

$hcPath = Join-Path $src 'ThemeResources/HighContrast.map'
$hc = @()
if (Test-Path -LiteralPath $hcPath) {
    $hc = Get-Content -LiteralPath $hcPath |
        Where-Object { $_ -and -not $_.StartsWith('#') } |
        ForEach-Object { $parts = $_ -split '=', 2; [pscustomobject]@{ Key = $parts[0]; Target = $parts[1] } }
}

$canonical = $rows | ForEach-Object { '{0}|{1}|{2}|{3}' -f $_.File, $_.Type, $_.Key, ($_.Target -replace '\s+', ' ') }
$hash = (Get-FileHash -InputStream ([IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes(($canonical -join "`n")))) -Algorithm SHA256).Hash.ToLower()

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Astra public resource keys')
$lines.Add('')
$lines.Add('<!-- Generated by tools/Report-AstraResourceKeys.ps1. Do not edit by hand: a hand edit is a claim')
$lines.Add('     the pipeline does not produce. Re-run the tool and commit both. -->')
$lines.Add('')
$lines.Add('Every row the layer publishes, in load order. `alias` is the `ResourceKey` a `StaticResource` row')
$lines.Add('points at - the alias layer only re-names a palette object, so overriding the alias moves every')
$lines.Add('control that reads it and nothing else. Literal rows carry their value. A style row carries its')
$lines.Add('`TargetType`; rows with no key are implicit styles and are listed by type only, because the')
$lines.Add('lookup is by type and an application cannot name them.')
$lines.Add('')
$lines.Add('Scope caveat: a keyed element written *inside* a template is listed as well, because it is a row in')
$lines.Add('the same file, but its lookup scope is that template - one `LinearGradientBrush` in')
$lines.Add('Styles/Common.jalxaml is the only such row today, and the count is the only place it shows up.')
$lines.Add('')
$paletteRows = @($rows | Where-Object { $_.Layer -eq 'palette' }).Count
$tokenRows = @($rows | Where-Object { $_.Layer -eq 'token' }).Count
$styleRows = @($rows | Where-Object { $_.Layer -eq 'style' }).Count
$lines.Add("Totals: $((@($rows).Count)) keyed or implicit rows in $($palette.Count + @($entries).Count) dictionaries " +
    "($paletteRows palette, $tokenRows token, $styleRows style), $((@($hc).Count)) high-contrast mapping rows.")
$lines.Add('')
$lines.Add('## Palette (generated by tools/Sync-AstraPalette.ps1)')
$lines.Add('')
foreach ($file in $palette) {
    $set = @($rows | Where-Object { $_.File -eq $file })
    if (-not $set) { continue }
    $lines.Add(('### {0} - {1} rows' -f $file, $set.Count))
    $lines.Add('')
    $lines.Add('| type | key | value or source |')
    $lines.Add('| --- | --- | --- |')
    foreach ($row in $set) { $lines.Add(('| {0} | `{1}` | `{2}` |' -f $row.Type, $row.Key, $row.Target)) }
    $lines.Add('')
}
$lines.Add(('### ThemeResources/HighContrast.map - {0} rows (the theme facade resolves these against SystemColors)' -f $hc.Count))
$lines.Add('')
$lines.Add('| key | system color |')
$lines.Add('| --- | --- |')
foreach ($row in $hc) { $lines.Add(('| `{0}` | `{1}` |' -f $row.Key, $row.Target)) }
$lines.Add('')
$lines.Add('## Dictionaries (Manifest.txt order)')
$lines.Add('')
foreach ($file in $entries) {
    $set = @($rows | Where-Object { $_.File -eq $file })
    $lines.Add(('### {0} - {1} rows' -f $file, $set.Count))
    $lines.Add('')
    if (-not $set) {
        $lines.Add('No keyed rows: the file is in the manifest to carry implicit styles only.')
        $lines.Add('')
        continue
    }
    $lines.Add('| type | key | target or value |')
    $lines.Add('| --- | --- | --- |')
    foreach ($row in $set) {
        $key = if ($row.Key) { ('`{0}`' -f $row.Key) } else { '*(implicit)*' }
        $lines.Add(('| {0} | {1} | `{2}` |' -f $row.Type, $key, $row.Target))
    }
    $lines.Add('')
}
$lines.Add(('<!-- canonical-lines={0} sha256={1} -->' -f @($canonical).Count, $hash))

$content = $lines -join "`r`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $out)) { Write-Error "$out is missing; run the tool without -Check."; exit 1 }
    $current = [IO.File]::ReadAllText($out)
    if ($current.Replace("`r`n", "`n") -ne $content.Replace("`r`n", "`n")) {
        Write-Host 'keys.md is stale. The inventory this run produced differs from the committed file.'
        $oldTail = [Regex]::Match($current, '<!-- canonical-lines=(\d+) sha256=([0-9a-f]+) -->')
        Write-Host ('committed: lines={0} sha256={1}' -f $oldTail.Groups[1].Value, $oldTail.Groups[2].Value)
        Write-Host ('current  : lines={0} sha256={1}' -f $canonical.Count, $hash)
        exit 1
    }
    Write-Host ('keys.md is current: {0} canonical lines.' -f $canonical.Count)
    exit 0
}

[IO.File]::WriteAllText($out, $content)
Write-Host ('Wrote {0}: {1} canonical lines, sha256 {2}.' -f $out, $canonical.Count, $hash)
