<#
.SYNOPSIS
  Generates docs/astra/audits/known-gaps.md - the full set of Known Gaps the Astra ledger states.
.DESCRIPTION
  Walks every markdown file under docs/astra and collects two things:

    1. every line that sits inside a heading whose text carries the marker "Known Gap" (the per-control
       "## 5. Known Gaps" sections an audit closes with, which is where gaps are actually enumerated);
    2. every line that carries the marker itself, so a gap written as prose outside such a section is
       still collected instead of silently missing.

  The marker is the contract: the branch discipline says "what cannot be done goes into Known Gaps, and an
  adjacent reading is not a substitute", so a gap neither stated nor marked is the thing this inventory
  exists to catch. Rows are truncated; `file:line` is the citation. Headings are never rows - a marker-carrying
  heading becomes the `###` group label that its rows are printed under.

  The tail of the file carries a canonical-row count and a SHA-256 over those rows. The serial gate and one
  xUnit fact recompute them, so this tool is how a deliberate change gets recorded:

    powershell -File tools/Report-AstraKnownGaps.ps1          # rewrite known-gaps.md
    powershell -File tools/Report-AstraKnownGaps.ps1 -Check   # exit 1 if it is stale

  Line numbers are part of the emitted rows, so editing a document above a collected line makes the
  inventory stale on purpose: re-run the tool and commit both, exactly as with keys.md.
#>
[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$docs = Join-Path $repo 'docs/astra'
$out = Join-Path $docs 'audits/known-gaps.md'
$marker = 'Known Gap'
$maxText = 200

$rows = [System.Collections.Generic.List[object]]::new()
$sections = 0
foreach ($path in (Get-ChildItem -LiteralPath $docs -Recurse -Filter *.md | Sort-Object FullName)) {
    $rel = ($path.FullName.Substring($docs.Length + 1) -replace '\\', '/')
    if ($rel -eq 'audits/known-gaps.md') { continue }

    $number = 0
    $sectionLevel = 0
    $sectionName = ''
    foreach ($line in [IO.File]::ReadAllLines($path.FullName)) {
        $number++
        $text = ($line -replace '\s+', ' ').Trim()
        if (-not $text) { continue }

        $heading = [Regex]::Match($text, '^(#{1,6})\s+(.*)$')
        if ($heading.Success) {
            $level = $heading.Groups[1].Value.Length
            if ($heading.Groups[2].Value.IndexOf($marker, [StringComparison]::Ordinal) -ge 0) {
                $sectionLevel = $level
                $sectionName = $heading.Groups[2].Value.Trim()
                $sections++
            }
            elseif ($sectionLevel -gt 0 -and $level -le $sectionLevel) {
                $sectionLevel = 0
                $sectionName = ''
            }
        }

        $inSection = $sectionLevel -gt 0
        $carries = $text.IndexOf($marker, [StringComparison]::Ordinal) -ge 0
        if (-not ($inSection -or $carries)) { continue }
        if ($heading.Success) {
            # A heading is structure, not a gap: a marker-carrying one is printed as the `###` group label over its
            # rows, so emitting it as a row too duplicated every section once and inflated the count.
            continue
        }
        if ($text -match '^\|\s*-{3,}') { continue }   # markdown table rule row

        if ($text.Length -gt $maxText) { $text = ($text.Substring(0, $maxText) + '...') }
        $rows.Add([pscustomobject]@{
                File = $rel; Line = $number; Section = $sectionName; Text = $text
            })
    }
}

$canonical = $rows | ForEach-Object { '{0}:{1}|{2}' -f $_.File, $_.Line, $_.Text }
$hash = (Get-FileHash -InputStream ([IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes(($canonical -join "`n")))) -Algorithm SHA256).Hash.ToLower()
$documents = @($rows | Select-Object -ExpandProperty File -Unique)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Astra known gaps - the full set the ledger states')
$lines.Add('')
$lines.Add('<!-- Generated by tools/Report-AstraKnownGaps.ps1. Do not edit by hand: a hand edit is a claim')
$lines.Add('     the ledger does not make. Re-run the tool and commit both. -->')
$lines.Add('')
$lines.Add('The rule this serves is in the branch discipline: what cannot be delivered or measured has to be')
$lines.Add('written down as a Known Gap, and an adjacent reading is not a substitute for it. So this document is')
$lines.Add('not a failure list - it is the evidence that the non-claims were made in the open, in one place, at')
$lines.Add('the file and line where each was made.')
$lines.Add('')
$lines.Add('Collected by the generator in two passes over every `docs/astra/**/*.md` line: a line inside a')
$lines.Add('heading whose text carries the marker `Known Gap`, plus any line that carries the marker itself')
$lines.Add('(prose-stated gaps are not allowed to hide outside a section). Rows are truncated to 200 characters;')
$lines.Add('the `file:line` pair is the citation, and a section heading is the label over its rows, not a row.')
$lines.Add('')
$lines.Add('What this CANNOT see is a limitation stated without the marker anywhere - "we do not claim X" in other')
$lines.Add('words is invisible here, so the count is a floor on candour, not a proof of completeness.')
$lines.Add('Categorised summaries live in `ROADMAP.md`.')
$lines.Add('')
$lines.Add(('{0} lines collected from {1} sections across {2} documents.' -f @($rows).Count, $sections, $documents.Count))
$lines.Add('')
foreach ($group in ($rows | Group-Object File)) {
    $lines.Add(('## {0} - {1} lines' -f $group.Name, @($group.Group).Count))
    $lines.Add('')
    $printed = ''
    foreach ($row in $group.Group) {
        if ($row.Section -and $row.Section -ne $printed) {
            $printed = $row.Section
            $lines.Add(('### {0}' -f $row.Section))
            $lines.Add('')
        }
        $lines.Add(('- `{0}:{1}` - {2}' -f $row.File, $row.Line, $row.Text))
    }
    $lines.Add('')
}
$lines.Add(('<!-- canonical-lines={0} sha256={1} -->' -f @($canonical).Count, $hash))

$content = $lines -join "`r`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $out)) { Write-Error "$out is missing; run the tool without -Check."; exit 1 }
    $current = [IO.File]::ReadAllText($out)
    if ($current.Replace("`r`n", "`n") -ne $content.Replace("`r`n", "`n")) {
        Write-Host 'known-gaps.md is stale. The inventory this run produced differs from the committed file.'
        $tail = [Regex]::Match($current, '<!-- canonical-lines=(\d+) sha256=([0-9a-f]+) -->')
        Write-Host ('committed: lines={0} sha256={1}' -f $tail.Groups[1].Value, $tail.Groups[2].Value)
        Write-Host ('current  : lines={0} sha256={1}' -f $canonical.Count, $hash)
        exit 1
    }
    Write-Host ('known-gaps.md is current: {0} canonical lines.' -f $canonical.Count)
    exit 0
}

[IO.File]::WriteAllText($out, $content)
Write-Host ('Wrote {0}: {1} canonical lines from {2} sections in {3} documents, sha256 {4}.' -f `
    $out, $canonical.Count, $sections, $documents.Count, $hash)
