param(
    [string]$SourceRoot = (Join-Path $PSScriptRoot '../../microsoft-ui-xaml'),
    [switch]$Check
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Xml.Linq
$pin = '19e3bdc3ccf3361393d623d3a5d2667cb8f33229'
$source = Join-Path $SourceRoot 'controls/dev/CommonStyles/Common_themeresources_any.xaml'
if ((& git -C $SourceRoot rev-parse HEAD) -ne $pin) { throw 'WinUI checkout does not match the recorded Astra source pin.' }
$document = [System.Xml.Linq.XDocument]::Load($source)
$x = [System.Xml.Linq.XNamespace]'http://schemas.microsoft.com/winfx/2006/xaml'
$ui = [System.Xml.Linq.XNamespace]'http://schemas.microsoft.com/winfx/2006/xaml/presentation'
$destination = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../src/FluentJalium/ThemeResources'))
if (-not $Check) { [System.IO.Directory]::CreateDirectory($destination) | Out-Null }
$sections = @{}
foreach ($entry in @(@('Light', 'Light'), @('Dark', 'Default'), @('HighContrast', 'HighContrast'))) {
    $sections[$entry[0]] = @($document.Root.Element($ui + 'ResourceDictionary.ThemeDictionaries').Elements() | Where-Object { $_.Attribute($x + 'Key').Value -eq $entry[1] })[0]
    if ($null -eq $sections[$entry[0]]) { throw "Missing upstream theme $($entry[1])" }
}
foreach ($theme in @('Light', 'Dark')) {
    $sourceTheme = if ($theme -eq 'Dark') { 'Default' } else { 'Light' }
    $section = $sections[$theme]
    $colors = @{}
    foreach ($node in $section.Elements($ui + 'Color')) {
        if ($node.Value.Trim() -match '^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$') { $colors[$node.Attribute($x + 'Key').Value] = $node.Value.Trim() }
    }
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('<!-- Copyright (c) Microsoft Corporation. MIT. Source: Common_themeresources_any.xaml @' + $pin + '. -->')
    $lines.Add('<!-- Generated by tools/Sync-AstraPalette.ps1. Platform accent references use the documented application accent; system colors are resolved at runtime. -->')
    $lines.Add('<ResourceDictionary xmlns="http://schemas.jalium.ui/2024" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
    foreach ($key in ($colors.Keys | Sort-Object)) { $lines.Add("  <Color x:Key=`"$key`">$($colors[$key])</Color>") }
    $brushes = [ordered]@{}
    foreach ($node in $section.Elements($ui + 'SolidColorBrush')) {
        $key = $node.Attribute($x + 'Key').Value
        $color = $node.Attribute('Color').Value
        if ($color -match '^\{(?:StaticResource|ThemeResource) ([^}]+)\}$') {
            $resource = $Matches[1]
            if ($colors.ContainsKey($resource)) { $color = $colors[$resource] }
            elseif ($resource -like 'SystemAccentColor*') { $color = if ($theme -eq 'Dark') { '#60CDFF' } else { '#0078D4' } }
            elseif ($resource -like 'SystemColor*') { $color = '#FF00FF' }
            else { throw "Unmapped upstream resource $resource for $key" }
        }
        $opacity = if ($node.Attribute('Opacity')) { $node.Attribute('Opacity').Value } else { '1' }
        $brushes[$key] = @($color, $opacity)
    }
    # Explicit Jalium adapters: solid popup fallback and the platform slider's outer stroke.
    $brushes['FlyoutPresenterBackgroundBrush'] = @($(if ($theme -eq 'Dark') { '#2C2C2C' } else { '#F9F9F9' }), '1')
    $brushes['ToolbarSurfaceBrush'] = @($(if ($theme -eq 'Dark') { '#2C2C2C' } else { '#FFFFFF' }), '1')
    $brushes['SliderThumbStrokeBrush'] = @($(if ($theme -eq 'Dark') { '#26000000' } else { '#24000000' }), '1')
    # 26.10.9 draws the scrollbar itself and reads two hard-coded brush names out of the application
    # resources rather than a ControlTemplate; docs/astra/audits/scrollbar.md measures which names
    # move pixels. They have to live in the palette because that is the only place the kernel
    # re-tints on a theme flip. Each one takes its value from the upstream token it stands in for,
    # so a palette change reaches it without a second literal to keep in step:
    # ScrollBarThumb   <- ScrollBarThumbFill  (ControlStrongFillColorDefault)
    # ScrollBarTrack   <- ScrollBarTrackFill, whose upstream AcrylicInAppFillColorDefault is a
    #                      backdrop material the framework cannot paint into its own track call, so
    #                      the resting state falls back to the transparent WinUI shows un-hovered.
    $hooks = [ordered]@{ ScrollBarThumb = 'ControlStrongFillColorDefaultBrush'; ScrollBarTrack = 'ControlFillColorTransparentBrush' }
    foreach ($hook in $hooks.GetEnumerator()) {
        if (-not $brushes.Contains($hook.Value)) { throw "ScrollBar hook $($hook.Key) resolves to missing upstream $($hook.Value)" }
        $brushes[$hook.Key] = $brushes[$hook.Value]
    }
    foreach ($key in ($brushes.Keys | Sort-Object)) { $lines.Add("  <SolidColorBrush x:Key=`"$key`" Color=`"$($brushes[$key][0])`" Opacity=`"$($brushes[$key][1])`" />") }
    $lines.Add('</ResourceDictionary>')
    $text = ($lines -join "`n") + "`n"
    $path = Join-Path $destination "$theme.jalxaml"
    if ($Check) {
        if (-not [System.IO.File]::Exists($path) -or [System.IO.File]::ReadAllText($path).Replace("`r`n", "`n") -ne $text) { throw "Palette drift: $path" }
    } else { [System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false)) }
    Write-Output "$theme : $($colors.Count) source colors, $($brushes.Count) resolved brushes; checked=$Check"
    if ($theme -eq 'Light') { $paletteKeys = @($brushes.Keys) }
}

# High contrast is WinUI's own per-key mapping, not an inference from key names. Every palette brush
# must appear, so a key added to the palette without an HC decision breaks the sync instead of
# silently falling back to a guess.
$highContrast = @{}
foreach ($node in $sections['HighContrast'].Elements($ui + 'SolidColorBrush')) {
    $key = $node.Attribute($x + 'Key').Value
    $color = $node.Attribute('Color').Value
    if ($color -match '^\{(?:StaticResource|ThemeResource) (SystemColor[A-Za-z]+)\}$') { $highContrast[$key] = $Matches[1] }
    elseif ($color -eq 'Transparent') { $highContrast[$key] = 'Transparent' }
    else { throw "Unmapped upstream high-contrast value '$color' for $key" }
}
# Explicit Jalium adapters, matching the solid-surface decision made for the light and dark palettes.
$highContrast['FlyoutPresenterBackgroundBrush'] = 'SystemColorWindowColor'
$highContrast['ToolbarSurfaceBrush'] = 'SystemColorWindowColor'
$highContrast['SliderThumbStrokeBrush'] = 'SystemColorWindowTextColor'
# The two ScrollBar hooks above, from the HighContrast branch of the same upstream file the
# aliases come from (ScrollBar_themeresources.xaml @19e3bdc3c). That branch states the system
# colour directly on its legacy rows: ScrollBarThumbBackgroundThemeBrush is
# {SystemColorButtonTextColor}, ScrollBarTrackBackgroundThemeBrush is {SystemColorButtonFaceColor}.
$highContrast['ScrollBarThumb'] = 'SystemColorButtonTextColor'
$highContrast['ScrollBarTrack'] = 'SystemColorButtonFaceColor'
$missing = @($paletteKeys | Where-Object { -not $highContrast.ContainsKey($_) })
if ($missing) { throw "No upstream high-contrast mapping for: $($missing -join ', ')" }
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Copyright (c) Microsoft Corporation. MIT. Source: Common_themeresources_any.xaml @' + $pin + ' (HighContrast branch).')
$lines.Add('# Generated by tools/Sync-AstraPalette.ps1. One line per palette brush key: key=<SystemColor* name | Transparent>,')
$lines.Add('# resolved against SystemColors at runtime. Keys absent here are not part of the Astra palette.')
foreach ($key in ($paletteKeys | Sort-Object)) { $lines.Add("$key=$($highContrast[$key])") }
$text = ($lines -join "`n") + "`n"
$path = Join-Path $destination 'HighContrast.map'
if ($Check) {
    if (-not [System.IO.File]::Exists($path) -or [System.IO.File]::ReadAllText($path).Replace("`r`n", "`n") -ne $text) { throw "Palette drift: $path" }
} else { [System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false)) }
$notPorted = @($highContrast.Keys | Where-Object { $paletteKeys -notcontains $_ } | Sort-Object)
Write-Output "HighContrast : $($paletteKeys.Count) mapped keys; upstream keys held back because the palette has no entry for them [$($notPorted -join ' ')]; checked=$Check"
