param(
    [string]$SourceRoot = (Join-Path $PSScriptRoot '../../microsoft-ui-xaml'),
    [switch]$Check
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Xml.Linq
$pin = '19e3bdc3ccf3361393d623d3a5d2667cb8f33229'
$source = Join-Path $SourceRoot 'controls/dev/CommonStyles/Common_themeresources_any.xaml'
if ((& git -C $SourceRoot rev-parse HEAD) -ne $pin) { throw 'WinUI checkout does not match the recorded Astra source pin.' }
$document = [System.Xml.Linq.XDocument]::Load($source)
$x = [System.Xml.Linq.XNamespace]'http://schemas.microsoft.com/winfx/2006/xaml'
$ui = [System.Xml.Linq.XNamespace]'http://schemas.microsoft.com/winfx/2006/xaml/presentation'
$destination = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../src/FluentJalium/Astra/Resources'))
if (-not $Check) { [System.IO.Directory]::CreateDirectory($destination) | Out-Null }
foreach ($theme in @('Light', 'Dark')) {
    $sourceTheme = if ($theme -eq 'Dark') { 'Default' } else { 'Light' }
    $section = @($document.Root.Element($ui + 'ResourceDictionary.ThemeDictionaries').Elements() | Where-Object { $_.Attribute($x + 'Key').Value -eq $sourceTheme })[0]
    if ($null -eq $section) { throw "Missing upstream theme $sourceTheme" }
    $colors = @{}
    foreach ($node in $section.Elements($ui + 'Color')) {
        if ($node.Value.Trim() -match '^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$') { $colors[$node.Attribute($x + 'Key').Value] = $node.Value.Trim() }
    }
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('<!-- Copyright (c) Microsoft Corporation. MIT. Source: Common_themeresources_any.xaml @' + $pin + '. -->')
    $lines.Add('<!-- Generated by tools/Sync-AstraPalette.ps1. Platform accent references use the documented application accent; system colors are resolved at runtime. -->')
    $lines.Add('<ResourceDictionary xmlns="http://schemas.jalium.ui/2024" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
    foreach ($key in ($colors.Keys | Sort-Object)) { $lines.Add("  <Color x:Key=`"$key`">$($colors[$key])</Color>") }
    $brushes = [ordered]@{}
    foreach ($node in $section.Elements($ui + 'SolidColorBrush')) {
        $key = $node.Attribute($x + 'Key').Value
        $color = $node.Attribute('Color').Value
        if ($color -match '^\{(?:StaticResource|ThemeResource) ([^}]+)\}$') {
            $resource = $Matches[1]
            if ($colors.ContainsKey($resource)) { $color = $colors[$resource] }
            elseif ($resource -like 'SystemAccentColor*') { $color = if ($theme -eq 'Dark') { '#60CDFF' } else { '#0078D4' } }
            elseif ($resource -like 'SystemColor*') { $color = '#FF00FF' }
            else { throw "Unmapped upstream resource $resource for $key" }
        }
        $opacity = if ($node.Attribute('Opacity')) { $node.Attribute('Opacity').Value } else { '1' }
        $brushes[$key] = @($color, $opacity)
    }
    # Explicit Jalium adapters: solid popup fallback and the platform slider's outer stroke.
    $brushes['FlyoutPresenterBackgroundBrush'] = @($(if ($theme -eq 'Dark') { '#2C2C2C' } else { '#F9F9F9' }), '1')
    $brushes['ToolbarSurfaceBrush'] = @($(if ($theme -eq 'Dark') { '#2C2C2C' } else { '#FFFFFF' }), '1')
    $brushes['SliderThumbStrokeBrush'] = @($(if ($theme -eq 'Dark') { '#26000000' } else { '#24000000' }), '1')
    foreach ($key in ($brushes.Keys | Sort-Object)) { $lines.Add("  <SolidColorBrush x:Key=`"$key`" Color=`"$($brushes[$key][0])`" Opacity=`"$($brushes[$key][1])`" />") }
    $lines.Add('</ResourceDictionary>')
    $text = ($lines -join "`n") + "`n"
    $path = Join-Path $destination "$theme.jalxaml"
    if ($Check) {
        if (-not [System.IO.File]::Exists($path) -or [System.IO.File]::ReadAllText($path).Replace("`r`n", "`n") -ne $text) { throw "Palette drift: $path" }
    } else { [System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false)) }
    Write-Output "$theme : $($colors.Count) source colors, $($brushes.Count) resolved brushes; checked=$Check"
}
