<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>FluentJalium.Gallery</RootNamespace>
    <AssemblyName>FluentJalium.Gallery</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultJalxamlItems>false</EnableDefaultJalxamlItems>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Astra/**/*.cs" />
    <JalxamlPage Include="Astra/**/*.jalxaml" />
    <ProjectReference Include="../../src/FluentJalium/FluentJalium.csproj" />
    <PackageReference Include="Jalium.UI.Desktop" Version="$(JaliumPackageVersion)" />
  </ItemGroup>
</Project>
